export const schedule = [
  {
    Band: 'Samba',
    Start: '1:45PM',
    End: '2:00PM',
    Location: 'Hankey St.',
  },
  {
    Band: 'The Illegal Smiles',
    Start: '2:00PM',
    End: '2:45PM',
    Location: '200 Eberle Ave.',
  },
  {
    Band: 'Sam Shaba & Band',
    Start: '2:15PM',
    End: '3:00PM',
    Location: '707 W. Wooster St.',
  },
  {
    Band: 'Bluegrass Ramplin/Rhythm',
    Start: '2:30PM',
    End: '3:15PM',
    Location: '223 Gorrell Ave.',
  },
  {
    Band: 'Extras',
    Start: '2:45PM',
    End: '3:30PM',
    Location: '250 Eberly Ave.',
  },
  {
    Band: 'Toraigh',
    Start: '3:00PM',
    End: '4:45PM',
    Location: '161 Eberly Ave.',
  },
  {
    Band: "It's Somewhat Humanoid",
    Start: '3:15PM',
    End: '4:00PM',
    Location: 'Arlyns Good Beer',
  },
  {
    Band: 'Jolly Gabbers',
    Start: '3:30PM',
    End: '4:15PM',
    Location: '254 Eberly Ave.',
  },
  {
    Band: 'Joe Baker Band',
    Start: '3:45PM',
    End: '4:30PM',
    Location: "Joe Baker's Garage",
  },
  {
    Band: 'Corduroy Road',
    Start: '4:00PM',
    End: '4:45PM',
    Location: '139 Eberly Ave.',
  },
  {
    Band: 'Rosa Cora Parry & Truth Untold',
    Start: '4:15PM',
    End: '5:00PM',
    Location: '255 Eberly Ave.',
  },
  {
    Band: 'Cigar Box Scott',
    Start: '4:30PM',
    End: '5:15PM',
    Location: 'Arlyns Good Beer',
  },
  {
    Band: 'Tree No Leaves',
    Start: '4:45PM',
    End: '5:30PM',
    Location: '204 Eberly Ave.',
  },
  {
    Band: 'Ginger & the Snaps',
    Start: '5:00PM',
    End: '5:45PM',
    Location: "Don's Garage",
  },
  {
    Band: 'Herbie & the Lovebugs',
    Start: '5:15PM',
    End: '6:00PM',
    Location: '140 Gorrell',
  },
  {
    Band: 'Grubs',
    Start: '5:30PM',
    End: '6:15PM',
    Location: '707 W. Wooster St.',
  },
  {
    Band: 'Tom Gorman & Friends',
    Start: '5:45PM',
    End: '6:30PM',
    Location: "Joe's or Don's Garage",
  },
  {
    Band: 'Kam Frankart',
    Start: '6:00PM',
    End: '6:45PM',
    Location: 'Arlyns Good Beer',
  },
  {
    Band: 'Freight Street',
    Start: '6:15PM',
    End: '7:00PM',
    Location: '208 Eberly Ave.',
  },
];
